version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
  gbex:
    build: .
    restart: always
    privileged: true
    command: bash -c "python manage.py migrate --noinput && python manage.py createinitialrevisions && python manage.py collectstatic --noinput && chmod -R 777 /code/shared/static && mkdir -p /code/shared/uploads && chmod -R 777 /code/shared/uploads && uwsgi --ini uwsgi.ini"
    volumes:
      - ./shared_volume:/code/shared
    depends_on:
      - db
    env_file:
      - .env
    ports:
    - "127.0.0.1:9000:9002"
volumes:
  pgdata: